{{- define "psb1-helm-base-chart.secret" -}}
{{- $ := index . 0 -}}
{{- $containerName := index . 1 -}}
{{- $containerValues := index ($.Values.containers) $containerName -}}
{{- if and $containerValues.enabled $containerValues.secret.enabled -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $containerName }}
  namespace: {{ $.Values.global.namespace | default "default" }}
  labels:
    {{- include "psb1-helm-base-chart.labels" (list $ $containerName) | nindent 4 }}
type: Opaque
stringData:
  {{- toYaml $containerValues.secret.stringData | nindent 2 }}
{{- end }}
{{- end -}}