{{- define "psb1-helm-base-chart.serviceaccount" -}}
{{- $ := index . 0 -}}
{{- $containerName := index . 1 -}}
{{- $containerValues := index ($.Values.containers) $containerName -}}
{{- if and $containerValues.enabled $.Values.global.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $containerName }}
  namespace: {{ $.Values.global.namespace | default "default" }}
  labels:
    {{- include "psb1-helm-base-chart.labels" (list $ $containerName) | nindent 4 }}
  {{- with $.Values.global.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end -}}